"""Markdown gap-report export for a stored evaluation run."""

from __future__ import annotations

from datetime import datetime, timezone

from app.evaluate import serialize_run
from app.models import EvaluationRun, Project


def _ts(dt: datetime) -> str:
    if dt.tzinfo is None:
        dt = dt.replace(tzinfo=timezone.utc)
    return dt.strftime("%Y-%m-%d %H:%M UTC")


def render_markdown(run: EvaluationRun, project: Project) -> str:
    data = serialize_run(run)
    lines: list[str] = []
    lines.append(f"# RegTrace-AI gap report — {project.name}")
    lines.append("")
    lines.append(f"- **Run ID:** `{data.id}`")
    lines.append(f"- **Project:** {project.name} (`{project.id}`)")
    lines.append(f"- **Frameworks:** {', '.join(data.frameworks)}")
    lines.append(f"- **Generator:** {data.generator} (no uncited claims allowed)")
    lines.append(f"- **Created:** {_ts(data.created_at)}")
    lines.append(f"- **Retrieved modules:** {data.module_count}")
    lines.append("")
    lines.append("## Licensing readiness")
    lines.append("")
    lines.append("| Framework | Covered | Partial | Missing | Total |")
    lines.append("|---|---:|---:|---:|---:|")
    for b in data.readiness:
        lines.append(f"| {b.framework} | {b.covered} | {b.partial} | {b.missing} | {b.total} |")
    lines.append("")
    lines.append("Every finding below is bound to a retrieved module locator. ")
    lines.append("Statuses: `grounded` (claim overlaps cited obligation), ")
    lines.append("`needs_human_verification` (partial evidence or weak overlap), ")
    lines.append("`unsupported` (failed citation validator).")
    lines.append("")
    lines.append("## Findings (source-traced)")
    lines.append("")
    for f in sorted(data.findings, key=lambda x: (x.framework, x.category)):
        cite = f.citations[0] if f.citations else None
        loc = f"{cite.article}" if cite else f.module_id
        if cite and cite.clause:
            loc += f" / {cite.clause}"
        lines.append(f"### {f.framework} · {f.category} · `{f.status}`")
        lines.append("")
        lines.append(f"- **Module:** `{f.module_id}`")
        lines.append(f"- **Confidence:** {f.confidence:.2f} (retrieval {f.retrieval_score:.2f})")
        lines.append(f"- **Coverage:** {f.coverage}")
        if cite:
            clause = f" — {cite.clause}" if cite.clause else ""
            lines.append(f"- **Citation:** [{cite.title} {cite.article}{clause}]({cite.url})")
        if f.flags:
            lines.append(f"- **Validator flags:** {', '.join(f.flags)}")
        if f.review_action:
            lines.append(f"- **HITL action:** {f.review_action}")
        lines.append("")
        lines.append(f.claim)
        lines.append("")
    lines.append("## Evidence gaps")
    lines.append("")
    for g in sorted(data.gaps, key=lambda x: (x.framework, x.coverage, x.category)):
        loc = ""
        if g.locator:
            loc = f"{g.locator.article}"
            if g.locator.clause:
                loc += f" / {g.locator.clause}"
        lines.append(f"### {g.framework} · {g.coverage} · {g.category} ({loc})")
        lines.append("")
        if g.obligation:
            lines.append(f"_{g.obligation}_")
            lines.append("")
        if g.present_items:
            lines.append("Present:")
            for item in g.present_items:
                lines.append(f"- {item}")
        if g.missing_items:
            lines.append("Missing:")
            for item in g.missing_items:
                lines.append(f"- {item}")
        lines.append("")
    if data.reviews:
        lines.append("## HITL overrides logged")
        lines.append("")
        for r in data.reviews:
            lines.append(
                f"- `{r.action}` on `{r.module_id}` at {_ts(r.created_at)}"
                + (f" — {r.note}" if r.note else "")
            )
            if r.override_text:
                lines.append(f"  - Override: {r.override_text}")
        lines.append("")
    lines.append("---")
    lines.append("Generated by RegTrace-AI. Citations link to official sources; paraphrases are original.")
    lines.append("")
    return "\n".join(lines)
