import type { Run } from "./types";
import { projectName } from "./demo-store";

function ts(iso: string): string {
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return iso;
  const pad = (n: number) => String(n).padStart(2, "0");
  return `${d.getUTCFullYear()}-${pad(d.getUTCMonth() + 1)}-${pad(d.getUTCDate())} ${pad(d.getUTCHours())}:${pad(d.getUTCMinutes())} UTC`;
}

export function renderMarkdown(run: Run): string {
  const lines: string[] = [];
  const name = projectName();
  lines.push(`# RegTrace-AI gap report — ${name}`);
  lines.push("");
  lines.push(`- **Run ID:** \`${run.id}\``);
  lines.push(`- **Project:** ${name} (\`${run.project_id}\`)`);
  lines.push(`- **Frameworks:** ${run.frameworks.join(", ")}`);
  lines.push(`- **Generator:** ${run.generator} (no uncited claims allowed)`);
  lines.push(`- **Created:** ${ts(run.created_at)}`);
  lines.push(`- **Retrieved modules:** ${run.module_count}`);
  lines.push("");
  lines.push("## Licensing readiness");
  lines.push("");
  lines.push("| Framework | Covered | Partial | Missing | Total |");
  lines.push("|---|---:|---:|---:|---:|");
  for (const b of run.readiness) {
    lines.push(`| ${b.framework} | ${b.covered} | ${b.partial} | ${b.missing} | ${b.total} |`);
  }
  lines.push("");
  lines.push("Every finding below is bound to a retrieved module locator. ");
  lines.push("Statuses: `grounded` (claim overlaps cited obligation), ");
  lines.push("`needs_human_verification` (partial evidence or weak overlap), ");
  lines.push("`unsupported` (failed citation validator).");
  lines.push("");
  lines.push("## Findings (source-traced)");
  lines.push("");
  const findings = [...run.findings].sort((a, b) =>
    a.framework === b.framework ? a.category.localeCompare(b.category) : a.framework.localeCompare(b.framework),
  );
  for (const f of findings) {
    const cite = f.citations[0];
    lines.push(`### ${f.framework} · ${f.category} · \`${f.status}\``);
    lines.push("");
    lines.push(`- **Module:** \`${f.module_id}\``);
    lines.push(`- **Confidence:** ${f.confidence.toFixed(2)} (retrieval ${f.retrieval_score.toFixed(2)})`);
    lines.push(`- **Coverage:** ${f.coverage}`);
    if (cite) {
      const clause = cite.clause ? ` — ${cite.clause}` : "";
      lines.push(`- **Citation:** [${cite.title} ${cite.article}${clause}](${cite.url})`);
    }
    if (f.flags.length) lines.push(`- **Validator flags:** ${f.flags.join(", ")}`);
    if (f.review_action) lines.push(`- **HITL action:** ${f.review_action}`);
    lines.push("");
    lines.push(f.claim);
    lines.push("");
  }
  lines.push("## Evidence gaps");
  lines.push("");
  const gaps = [...run.gaps].sort((a, b) => {
    if (a.framework !== b.framework) return a.framework.localeCompare(b.framework);
    if (a.coverage !== b.coverage) return a.coverage.localeCompare(b.coverage);
    return a.category.localeCompare(b.category);
  });
  for (const g of gaps) {
    let loc = "";
    if (g.locator) {
      loc = g.locator.article;
      if (g.locator.clause) loc += ` / ${g.locator.clause}`;
    }
    lines.push(`### ${g.framework} · ${g.coverage} · ${g.category} (${loc})`);
    lines.push("");
    if (g.obligation) {
      lines.push(`_${g.obligation}_`);
      lines.push("");
    }
    if (g.present_items.length) {
      lines.push("Present:");
      for (const item of g.present_items) lines.push(`- ${item}`);
    }
    if (g.missing_items.length) {
      lines.push("Missing:");
      for (const item of g.missing_items) lines.push(`- ${item}`);
    }
    lines.push("");
  }
  if (run.reviews.length) {
    lines.push("## HITL overrides logged");
    lines.push("");
    for (const r of run.reviews) {
      lines.push(
        `- \`${r.action}\` on \`${r.module_id}\` at ${ts(r.created_at)}` +
          (r.note ? ` — ${r.note}` : ""),
      );
      if (r.override_text) lines.push(`  - Override: ${r.override_text}`);
    }
    lines.push("");
  }
  lines.push("---");
  lines.push("Generated by RegTrace-AI. Citations link to official sources; paraphrases are original.");
  lines.push("");
  return lines.join("\n");
}
